import { SBC } from './types';

// Realistic mock SBC data matching FC26 market values (coins)
// Pack expected values based on typical FC26 market rates
export const MOCK_SBCS: SBC[] = [
  {
    id: 'fc26-1',
    name: 'FC26 Foundations I',
    description: 'Build a basic squad to get started.',
    category: 'foundation',
    rewards: [{ type: 'pack', name: 'Small Gold Pack', amount: 1, estimatedValue: 1500 }],
    requirements: [{ minRating: 65, chemistry: 15, squadSize: 11, description: 'Min Rating: 65, 15 Chem' }],
    estimatedCost: 800,
    totalRewardValue: 1500,
    costBenefitRatio: 1.88,
    repeatable: false,
    endDate: '2026-07-31',
    difficulty: 'Easy',
    source: 'mock',
  },
  {
    id: 'fc26-2',
    name: 'FC26 Foundations II',
    description: 'Intermediate squad challenge.',
    category: 'foundation',
    rewards: [{ type: 'pack', name: 'Gold Pack', amount: 1, estimatedValue: 2500 }],
    requirements: [{ minRating: 70, chemistry: 20, squadSize: 11, description: 'Min Rating: 70, 20 Chem' }],
    estimatedCost: 1800,
    totalRewardValue: 2500,
    costBenefitRatio: 1.39,
    repeatable: false,
    endDate: '2026-07-31',
    difficulty: 'Easy',
    source: 'mock',
  },
  {
    id: 'fc26-3',
    name: 'Mid Rollers',
    description: 'A balanced challenge for mid-tier squads.',
    category: 'foundation',
    rewards: [{ type: 'pack', name: 'Rare Gold Pack', amount: 1, estimatedValue: 3200 }],
    requirements: [{ minRating: 74, chemistry: 22, squadSize: 11, description: 'Min Rating: 74, 22 Chem' }],
    estimatedCost: 3500,
    totalRewardValue: 3200,
    costBenefitRatio: 0.91,
    repeatable: false,
    endDate: '2026-07-31',
    difficulty: 'Medium',
    source: 'mock',
  },
  {
    id: 'fc26-4',
    name: 'League Hybrid: Premier League',
    description: 'Build a hybrid squad featuring Premier League players.',
    category: 'hybrid',
    rewards: [{ type: 'pack', name: 'Premium Gold Pack', amount: 1, estimatedValue: 5500 }],
    requirements: [
      { minRating: 75, chemistry: 22, uniqueLeagues: 2, description: 'Min Rating: 75, 22 Chem, 2+ Leagues' },
    ],
    estimatedCost: 4200,
    totalRewardValue: 5500,
    costBenefitRatio: 1.31,
    repeatable: false,
    endDate: '2026-06-15',
    difficulty: 'Medium',
    source: 'mock',
  },
  {
    id: 'fc26-5',
    name: 'Nation Mix: Brazil',
    description: 'Field a squad with Brazilian flair.',
    category: 'nations',
    rewards: [
      { type: 'pack', name: 'Rare Gold Pack', amount: 2, estimatedValue: 6400 },
    ],
    requirements: [
      { minRating: 76, chemistry: 20, sameNation: false, uniqueNations: 5, description: 'Min Rating: 76, 5+ Nations' },
    ],
    estimatedCost: 5100,
    totalRewardValue: 6400,
    costBenefitRatio: 1.25,
    repeatable: false,
    endDate: '2026-06-30',
    difficulty: 'Medium',
    source: 'mock',
  },
  {
    id: 'fc26-6',
    name: 'Path to Glory: Segment 1',
    description: 'First step on the road to glory — repeatable for steady profit.',
    category: 'upgrades',
    rewards: [{ type: 'pack', name: 'Prime Electrum Players Pack', amount: 1, estimatedValue: 18000 }],
    requirements: [
      { minRating: 77, chemistry: 25, squadSize: 11, description: 'Min Rating: 77, Full Chem' },
    ],
    estimatedCost: 8500,
    totalRewardValue: 18000,
    costBenefitRatio: 2.12,
    repeatable: true,
    endDate: '2026-08-01',
    difficulty: 'Medium',
    source: 'mock',
  },
  {
    id: 'fc26-7',
    name: 'Champions Path',
    description: 'High-value challenge for experienced traders.',
    category: 'upgrades',
    rewards: [
      { type: 'pack', name: 'Rare Players Pack', amount: 1, estimatedValue: 20000 },
      { type: 'pack', name: 'Rare Gold Pack', amount: 1, estimatedValue: 3200 },
    ],
    requirements: [{ minRating: 80, chemistry: 25, squadSize: 11, description: 'Min Rating: 80, Full Chem' }],
    estimatedCost: 15000,
    totalRewardValue: 23200,
    costBenefitRatio: 1.55,
    repeatable: false,
    endDate: '2026-06-20',
    difficulty: 'Hard',
    source: 'mock',
  },
  {
    id: 'fc26-8',
    name: 'La Liga Devotion',
    description: 'Showcase Spanish league talent.',
    category: 'leagues',
    rewards: [{ type: 'pack', name: 'Mega Pack', amount: 1, estimatedValue: 28000 }],
    requirements: [
      { minRating: 82, chemistry: 22, sameLeague: true, description: 'Min Rating: 82, La Liga only' },
    ],
    estimatedCost: 24000,
    totalRewardValue: 28000,
    costBenefitRatio: 1.17,
    repeatable: false,
    endDate: '2026-07-10',
    difficulty: 'Hard',
    source: 'mock',
  },
  {
    id: 'fc26-9',
    name: 'Bundesliga Brilliance',
    description: 'German engineering on the pitch.',
    category: 'leagues',
    rewards: [{ type: 'pack', name: 'Mega Pack', amount: 1, estimatedValue: 28000 }],
    requirements: [
      { minRating: 82, chemistry: 22, sameLeague: true, description: 'Min Rating: 82, Bundesliga only' },
    ],
    estimatedCost: 22000,
    totalRewardValue: 28000,
    costBenefitRatio: 1.27,
    repeatable: false,
    endDate: '2026-07-10',
    difficulty: 'Hard',
    source: 'mock',
  },
  {
    id: 'fc26-10',
    name: 'Daily Bronze Upgrade',
    description: 'Convert surplus bronze cards into silver packs — pure profit.',
    category: 'upgrades',
    rewards: [{ type: 'pack', name: 'Silver Pack', amount: 1, estimatedValue: 600 }],
    requirements: [{ bronzeCards: 11, description: '11 Bronze Players' }],
    estimatedCost: 110,
    totalRewardValue: 600,
    costBenefitRatio: 5.45,
    repeatable: true,
    endDate: '2026-12-31',
    difficulty: 'Easy',
    source: 'mock',
  },
  {
    id: 'fc26-11',
    name: 'Silver to Gold Upgrade',
    description: 'Turn silver scraps into gold. Extremely efficient.',
    category: 'upgrades',
    rewards: [{ type: 'pack', name: 'Rare Gold Pack', amount: 1, estimatedValue: 3200 }],
    requirements: [{ silverCards: 11, description: '11 Silver Players' }],
    estimatedCost: 900,
    totalRewardValue: 3200,
    costBenefitRatio: 3.56,
    repeatable: true,
    endDate: '2026-12-31',
    difficulty: 'Easy',
    source: 'mock',
  },
  {
    id: 'fc26-12',
    name: 'FUT Birthday Squad',
    description: 'Celebrate FUT Birthday with a top-tier squad.',
    category: 'promo',
    rewards: [
      { type: 'pack', name: 'FUT Birthday Pack', amount: 1, estimatedValue: 45000 },
    ],
    requirements: [{ minRating: 85, chemistry: 23, squadSize: 11, description: 'Min Rating: 85, 23 Chem' }],
    estimatedCost: 60000,
    totalRewardValue: 45000,
    costBenefitRatio: 0.75,
    repeatable: false,
    endDate: '2026-06-01',
    difficulty: 'Expert',
    source: 'mock',
  },
  {
    id: 'fc26-13',
    name: 'TOTW Upgrade',
    description: 'Grind toward a TOTW player — great long-term value.',
    category: 'upgrades',
    rewards: [{ type: 'pack', name: 'TOTW Pack', amount: 1, estimatedValue: 55000 }],
    requirements: [{ minRating: 83, chemistry: 25, rareCards: 11, description: 'Min Rating: 83, 11 Rares, Full Chem' }],
    estimatedCost: 38000,
    totalRewardValue: 55000,
    costBenefitRatio: 1.45,
    repeatable: false,
    endDate: '2026-07-20',
    difficulty: 'Hard',
    source: 'mock',
  },
  {
    id: 'fc26-14',
    name: 'Serie A Legends',
    description: 'Italian football masterclass.',
    category: 'leagues',
    rewards: [
      { type: 'pack', name: 'Prime Gold Players Pack', amount: 1, estimatedValue: 65000 },
    ],
    requirements: [
      { minRating: 84, chemistry: 22, sameLeague: true, description: 'Min Rating: 84, Serie A only' },
    ],
    estimatedCost: 55000,
    totalRewardValue: 65000,
    costBenefitRatio: 1.18,
    repeatable: false,
    endDate: '2026-06-25',
    difficulty: 'Expert',
    source: 'mock',
  },
  {
    id: 'fc26-15',
    name: 'Icon Moments: Legends',
    description: 'The ultimate challenge — worth it only for the best squads.',
    category: 'icons',
    rewards: [
      { type: 'player', name: 'Icon Player Pick (Mid)', amount: 1, estimatedValue: 400000 },
    ],
    requirements: [{ minRating: 88, chemistry: 25, squadSize: 11, description: 'Min Rating: 88, Full Chem' }],
    estimatedCost: 450000,
    totalRewardValue: 400000,
    costBenefitRatio: 0.89,
    repeatable: false,
    endDate: '2026-06-10',
    difficulty: 'Expert',
    source: 'mock',
  },
];
